name: CI

on: [push, pull_request]

jobs:
  Cpp-Lint:
      name: lint
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
      
      - uses: DoozyX/clang-format-lint-action@v0.12
        with:
          source: 'src/'
          extensions: 'h,cpp'
          clangFormatVersion: 10
          style: WebKit